### PR TITLE
feature: add flag use class extension in TypeDeclarationSourceGenerator

### PR DESCRIPTION
**Pull request by Sassine**

### CODE REVIEW

**Comment by Sassine** [comment]
Some Annotations receive their parameter as the value of the name of the class and the extension ".class", currently to make this injection it is necessary to import the class and define its type as a string containing the name and .class. With this feature, just enable the flag that will do both the import and render the name with ".class"

**Comment by Roberto-Gentili** [comment]
Hi, thanks for the help, can you post a minimal example to reproduce the error?

**Comment by Roberto-Gentili** [comment]
> Some Annotations receive their parameter as the value of the name of the class and the extension ".class", currently to make this injection it is necessary to import the class and define its type as a string containing the name and .class. With this feature, just enable the flag that will do both the import and render the name with ".class"

You can solve as follow:

```java
AnnotationSourceGenerator.create(NotEmpty.class).addParameter(
	VariableSourceGenerator.create("message").setValue("\"Person name should not be empty\"")
).addParameter(
	VariableSourceGenerator.create("groups").setValue(this.getClass().getSimpleName() + ".class").useType(this.getClass())
)
```

Here the [complete example](https://github.com/burningwave/core/blob/e26f1d7062c7bb68655f648520686c00de902e9c/src/test/java/org/burningwave/core/UnitSourceGeneratorTest.java#L173)

**Comment by Roberto-Gentili** [comment]
You can solve with the VariableSourceGenerator as follow:

```java
AnnotationSourceGenerator.create(NotEmpty.class).addParameter(
	VariableSourceGenerator.create("message").setValue("\"Person name should not be empty\"")
).addParameter(
	VariableSourceGenerator.create("groups").setValue(this.getClass().getSimpleName() + ".class").useType(this.getClass())
)
```

Here the [complete example](https://github.com/burningwave/core/blob/e26f1d7062c7bb68655f648520686c00de902e9c/src/test/java/org/burningwave/core/UnitSourceGeneratorTest.java#L173). The `org.burningwave.core.UnitSourceGeneratorTest` class contains a series of tests that together represent a complete example of what you can do with source generators.

**Pull request closed without merging**
