### PR TITLE
Refactored some code

### PR DESCRIPTION
**Pull request by Himanshu032000**

### CODE REVIEW

**Comment by Himanshu032000** [comment]
Refactored some code at a design level to have better readability of a design.

**Comment by Roberto-Gentili** [comment]
Could you run the [tests](https://github.com/burningwave/core/actions/workflows/%5BA%5D%20build%20and%20test,%20release%20if%20requested.yml) and verify that everything works?

**Comment by Himanshu032000** [comment]
I ran all the tests locally and also checked the [tests](https://github.com/burningwave/core/actions/runs/4587250056) and everything looks good.

**Comment by Himanshu032000** [comment]
Hello @Roberto-Gentili, Could you please merge this if everything looks good?

Thanks in advance!

**Pull request closed without merging**
